# Generated by Django 4.1.7 on 2023-04-28 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coursename", models.CharField(max_length=256)),
                ("course_id", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("class_start_time", models.TimeField()),
                ("class_end_time", models.TimeField()),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("Mon", "Mon"),
                            ("Tues", "Tues"),
                            ("Wed", "Wed"),
                            ("Thurs", "Thurs"),
                            ("Fri", "Fri"),
                            ("Sat", "Sat"),
                            ("Sun", "Sun"),
                            ("Mon,Wed,Fri", "Mon,Wed,Fri"),
                            ("Mon,Wed", "Mon,Wed"),
                            ("Tues,Thurs", "Tues,Thurs"),
                        ],
                        max_length=255,
                    ),
                ),
                ("meeting_days", models.CharField(max_length=255)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        related_name="courses_taken", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "userid",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "is_instructor",
                    models.CharField(
                        choices=[("student", "Student"), ("instructor", "Instructor")],
                        default="student",
                        max_length=10,
                    ),
                ),
                ("username", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="in_course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.course",
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("qrid", models.AutoField(primary_key=True, serialize=False)),
                ("class_code", models.CharField(max_length=64)),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "course_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.course",
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.user",
                    ),
                ),
            ],
        ),
    ]
