# Generated by Django 4.2.1 on 2023-05-09 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=256)),
                ('course_id', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('class_start_time', models.TimeField()),
                ('class_end_time', models.TimeField()),
                ('day_of_week', models.CharField(choices=[('Mon', 'Mon'), ('Tues', 'Tues'), ('Wed', 'Wed'), ('Thurs', 'Thurs'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun'), ('Mon,Wed,Fri', 'Mon,Wed,Fri'), ('Mon,Wed', 'Mon,Wed'), ('Tues,Thurs', 'Tues,Thurs')], max_length=255)),
                ('meeting_days', models.CharField(max_length=255)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='courses_taken', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_instructor', models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor')], default='student', max_length=10)),
                ('username', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('qrid', models.AutoField(primary_key=True, serialize=False)),
                ('class_code', models.CharField(max_length=64)),
                ('time', models.DateTimeField()),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='addqrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('qr_code_image', models.ImageField(upload_to='qrcodes/')),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='in_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_id', models.ForeignKey(default='default_course_id', on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('course_id', 'student')},
            },
        ),
    ]
