# Generated by Django 4.1.7 on 2023-03-29 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('coursename', models.CharField(max_length=256)),
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('username', models.CharField(max_length=256)),
                ('userid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='qrCode',
            fields=[
                ('qrid', models.AutoField(primary_key=True, serialize=False)),
                ('courseid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.courses')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='in_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_instructor', models.BooleanField()),
                ('courseid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.courses')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user')),
            ],
        ),
    ]
