# Generated by Django 4.1.7 on 2023-04-28 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_course',
            name='enrollment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='in_course',
            name='student',
            field=models.ForeignKey(default='default_student', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='in_course',
            name='course_id',
            field=models.ForeignKey(default='default_course_id', on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AlterUniqueTogether(
            name='in_course',
            unique_together={('course_id', 'student')},
        ),
        migrations.RemoveField(
            model_name='in_course',
            name='userid',
        ),
    ]
