# Generated by Django 4.1.7 on 2023-04-24 14:10

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_course_class_end_time_course_class_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='meeting_days',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses_taken', to=settings.AUTH_USER_MODEL),
        ),
    ]
