# Generated by Django 4.2.1 on 2023-05-10 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_attendance_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='addqrcode',
            name='class_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.attendance'),
        ),
    ]
