# Generated by Django 4.1.7 on 2023-04-24 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_courseid_attendance_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='class_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
