# Generated by Django 4.1.7 on 2023-04-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_attendance_class_code_alter_attendance_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("Mon", "Mon"),
                    ("Tues", "Tues"),
                    ("Wed", "Wed"),
                    ("Thurs", "Thurs"),
                    ("Fri", "Fri"),
                    ("Sat", "Sat"),
                    ("Sun", "Sun"),
                    ("Mon,Wed,Fri", "Mon,Wed,Fri"),
                    ("Mon,Wed", "Mon,Wed"),
                    ("Tues,Thurs", "Tues,Thurs"),
                ],
                max_length=255,
            ),
        ),
    ]
