# Generated by Django 4.1.7 on 2023-04-25 02:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_attendance_class_code_alter_attendance_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course", old_name="coursename", new_name="course_name",
        ),
        migrations.RemoveField(model_name="course", name="id",),
        migrations.AddField(
            model_name="course",
            name="course_code",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="course_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
