# Generated by Django 4.1.7 on 2023-04-25 02:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_rename_coursename_course_course_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course", old_name="course_code", new_name="courseid",
        ),
        migrations.RenameField(
            model_name="course", old_name="course_name", new_name="coursename",
        ),
        migrations.RemoveField(model_name="course", name="course_id",),
        migrations.AddField(
            model_name="course",
            name="id",
            field=models.AutoField(
                default=django.utils.timezone.now, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
    ]
